# Generated by Django 3.2.5 on 2022-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceld_order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders_count',
            name='date',
            field=models.DateField(),
        ),
    ]
