# Generated by Django 3.2.5 on 2022-09-24 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 24, 5, 48, 32, 200968, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
