# Generated by Django 3.2.5 on 2022-09-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='files/image/image0.png', null=True, upload_to='files/image'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
