# Generated by Django 3.2.5 on 2022-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='number_of_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
