# Generated by Django 3.2.5 on 2022-09-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
