# Generated by Django 3.2.5 on 2023-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='files/image/image0.png', null=True, upload_to='files/image'),
        ),
    ]
